//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 01:45:39 PM CEST 
//


package pl.edu.icm.maven.oozie.plugin.pigscripts.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for depsProjectPigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="depsProjectPigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="all-scripts" type="{}scriptHandlingType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "depsProjectPigType", propOrder = {
    "allScripts"
})
public class DepsProjectPigType {

    @XmlElement(name = "all-scripts", required = true)
    protected ScriptHandlingType allScripts;

    /**
     * Gets the value of the allScripts property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptHandlingType }
     *     
     */
    public ScriptHandlingType getAllScripts() {
        return allScripts;
    }

    /**
     * Sets the value of the allScripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptHandlingType }
     *     
     */
    public void setAllScripts(ScriptHandlingType value) {
        this.allScripts = value;
    }

}
