//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 06:42:28 PM CET 
//


package pl.edu.icm.maven.oozie.plugin.pigscripts.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scriptHandlingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scriptHandlingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="srcProject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="root" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preserve" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mainDirAsDst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="includes" type="{}includesType"/>
 *         &lt;element name="excludes" type="{}excludesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scriptHandlingType", propOrder = {
    "srcProject",
    "root",
    "preserve",
    "target",
    "mainDirAsDst",
    "includes",
    "excludes"
})
public class ScriptHandlingType {

    @XmlElement(defaultValue = ".*")
    protected String srcProject;
    @XmlElement(required = true, defaultValue = "pig")
    protected String root;
    @XmlElement(defaultValue = "false")
    protected Boolean preserve;
    @XmlElement(defaultValue = "")
    protected String target;
    @XmlElement(defaultValue = "false")
    protected Boolean mainDirAsDst;
    @XmlElement(required = true)
    protected IncludesType includes;
    protected ExcludesType excludes;

    /**
     * Gets the value of the srcProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcProject() {
        return srcProject;
    }

    /**
     * Sets the value of the srcProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcProject(String value) {
        this.srcProject = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }

    /**
     * Gets the value of the preserve property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPreserve() {
        return preserve;
    }

    /**
     * Sets the value of the preserve property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreserve(Boolean value) {
        this.preserve = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the mainDirAsDst property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMainDirAsDst() {
        return mainDirAsDst;
    }

    /**
     * Sets the value of the mainDirAsDst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMainDirAsDst(Boolean value) {
        this.mainDirAsDst = value;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link IncludesType }
     *     
     */
    public IncludesType getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludesType }
     *     
     */
    public void setIncludes(IncludesType value) {
        this.includes = value;
    }

    /**
     * Gets the value of the excludes property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludesType }
     *     
     */
    public ExcludesType getExcludes() {
        return excludes;
    }

    /**
     * Sets the value of the excludes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludesType }
     *     
     */
    public void setExcludes(ExcludesType value) {
        this.excludes = value;
    }

}
